services:
  - type: web
    name: eduscan-somalia
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        fromParam: PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PIP_NO_CACHE_DIR
        value: "1"