services:
  - type: web
    name: eduscan-somalia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        fromParam: PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0